### ISSUE TITLE
SIGILL when throwing an exception

### ISSUE THREAD

**Issue by gaa-cifasis** [Microsoft/ChakraCore#1922]
Hi,

We found an odd crash of the ChakraCore interpreter (ch) when you "throw a float". It was tested in ArchLinux using revision 627e01bc65455b2dad495bd311a2eced7417e97f. 

To reproduce:
```
$ echo "throw 1.1;" > sigill.js
$ gdb --args ./ch sigill.js
...
Thread 1 "ch" received signal SIGILL, Illegal instruction.
0x00007ffff48832fd in Js::FDblToRgbFast (dbl=1.1000000000000001, 
    prgb=0x7fffffffd5a0 "\001\001\377\377\377\177", pwExp10=0x7fffffffd5e0, ppbLim=0x7fffffffd598, 
    nDigits=-1) at /home/g/Work/Code/ChakraCore/lib/Common/Common/NumberUtilities_strtod.cpp:1592
1592	        if (wExp2 >= 1023 && wExp2 <= 1075 && dbl == floor(dbl))
(gdb) bt
#0  0x00007ffff48832fd in Js::FDblToRgbFast (dbl=1.1000000000000001, 
    prgb=0x7fffffffd5a0 "\001\001\377\377\377\177", pwExp10=0x7fffffffd5e0, ppbLim=0x7fffffffd598, 
    nDigits=-1) at /home/g/Work/Code/ChakraCore/lib/Common/Common/NumberUtilities_strtod.cpp:1592
#1  0x00007ffff4888483 in Js::NumberUtilities::FNonZeroFiniteDblToStr (dbl=1.1000000000000001, 
    pchDst=0x7fffffffd610 u"1.1", cchDst=256)
    at /home/g/Work/Code/ChakraCore/lib/Common/Common/NumberUtilities_strtod.cpp:2452
#2  0x00007ffff51c14b1 in Js::JavascriptNumber::ToStringRadix10 (value=1.1000000000000001, 
    scriptContext=0x555555910d10)
    at /home/g/Work/Code/ChakraCore/lib/Runtime/Library/JavascriptNumber.cpp:928
#3  0x00007ffff4eece7c in Js::JavascriptConversion::ToString (aValue=0xc00d99999999999a, 
    scriptContext=0x555555910d10)
    at /home/g/Work/Code/ChakraCore/lib/Runtime/Language/JavascriptConversion.cpp:621
#4  0x00007ffff4424c17 in JsConvertValueToString::$_21::operator() (this=0x7fffffffdba8, 
    scriptContext=0x555555910d10) at /home/g/Work/Code/ChakraCore/lib/Jsrt/Jsrt.cpp:1139
#5  0x00007ffff440026a in ContextAPIWrapper<true, JsConvertValueToString::$_21> (fn=...)
    at /home/g/Work/Code/ChakraCore/lib/Jsrt/JsrtInternal.h:139
#6  0x00007ffff440016d in JsConvertValueToString (value=0xc00d99999999999a, result=0x7fffffffdfd0)
    at /home/g/Work/Code/ChakraCore/lib/Jsrt/Jsrt.cpp:1132
#7  0x00005555555685a8 in ChakraRTInterface::JsConvertValueToString (value=0xc00d99999999999a, 
    stringValue=0x7fffffffdfd0) at /home/g/Work/Code/ChakraCore/bin/ch/ChakraRtInterface.h:304
#8  0x000055555556e2cb in WScriptJsrt::PrintException (fileName=0x5555558db860 "sigill.js", 
    jsErrorCode=JsErrorScriptException) at /home/g/Work/Code/ChakraCore/bin/ch/WScriptJsrt.cpp:1006
#9  0x000055555555e34c in RunScript (fileName=0x5555558db860 "sigill.js", 
    fileContents=0x5555558cfc10 "throw 1.1;\n", bcBuffer=0x0, 
---Type <return> to continue, or q <return> to quit---
    fullPath=0x7fffffffe520 "/home/g/work/code/chakracore/buildlinux/debug/sigill.js")
    at /home/g/Work/Code/ChakraCore/bin/ch/ch.cpp:342
#10 0x000055555555f4f6 in ExecuteTest (fileName=0x5555558db860 "sigill.js")
    at /home/g/Work/Code/ChakraCore/bin/ch/ch.cpp:587
#11 0x000055555555f5e0 in ExecuteTestWithMemoryCheck (fileName=0x5555558db860 "sigill.js")
    at /home/g/Work/Code/ChakraCore/bin/ch/ch.cpp:635
#12 0x000055555555fb20 in main (argc=2, c_argv=0x7fffffffe868)
    at /home/g/Work/Code/ChakraCore/bin/ch/ch.cpp:862
```

This issue was found using QuickFuzz.

Regards,
Gustavo.

**Comment by obastemur** [comment]
@gaa-cifasis I'm unable to reproduce this issue on Ubuntu, OSX, Fedora.

From your comment; looks like it fails on `floor` call.
It might be because of the OS itself ?

**Comment by gaa-cifasis** [comment]
I dont know. Just in case, i'm compiling using gcc 6.2.1 and ChakraCore is failing here:

    (gdb) x/i $rip
    => 0x7ffff48832fd <Js::FDblToRgbFast(double, unsigned char*, int*, unsigned char**, int)+509>:	
    roundsd $0x9,%xmm1,%xmm2

**Comment by obastemur** [comment]
Could you please send the outputs for the commands below;

```
/sbin/ldconfig -p
```

```
cat /proc/version
```

Thanks

**Comment by gaa-cifasis** [comment]
Sure thing!

[ldconfig.txt](https://github.com/Microsoft/ChakraCore/files/573172/ldconfig.txt)
[proc-version.txt](https://github.com/Microsoft/ChakraCore/files/573171/proc-version.txt)

**Comment by obastemur** [comment]
I have installed arch-linux during the weekend and tested the case above.
It works without a problem. I also see ChakraCore tests cases are passing on Arch-Linux.

I'm really happy to see ChakraCore works on one another Linux distro.

```
Linux version 4.8.6-1-ARCH (builduser@tobias) (gcc version 6.2.1 20160830 (GCC) ) #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016
```

One thing for sure, ArchLinux (latest) defaults to clang 3.9 on `pacman`. 
We have a compatibility issue with Clang 3.9 and I'm about to send a PR for that fix.

Thanks for the report. At this point I'm unable to do anything else. I suggest you to update to latest Arch-Linux (if it is possible and sync to latest master after the Clang 3.9 PR)

**Comment by obastemur** [comment]
@gaa-cifasis FYI; https://github.com/Microsoft/ChakraCore/pull/1930
