### ISSUE TITLE
Assertion failure: "Deferring function parsing of a function does not handle lambda syntax" with "use asm" and arrow function

### ISSUE THREAD

**Issue by nth10sd** [Microsoft/ChakraCore#2237]
```
(function() {
    "use asm";
    m => 0;
})()
```

$ ~/chakracore/BuildLinux/Debug/ch 1case.js 
ASSERTION 65750: (/home/skywinlinvm/chakracore/lib/Parser/Parse.cpp, line 5147) Deferring function parsing of a function does not handle lambda syntax
 Failure: (!fLambda)
Illegal instruction (core dumped)

$ file ~/chakracore/BuildLinux/Debug/ch
/home/skywinlinvm/chakracore/BuildLinux/Debug/ch: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32

Git hash: 37690535b2ba477a5deeb421dab55f5344932db1
OS: Ubuntu Linux 16.04.1 LTS
Arch: x86_64

```
ASSERTION 65789: (/home/skywinlinvm/chakracore/lib/Parser/Parse.cpp, line 5147) Deferring function parsing of a function does not handle lambda syntax
 Failure: (!fLambda)

Thread 1 "ch" received signal SIGILL, Illegal instruction.
0x00007ffff5ce855a in Parser::ParseFncDeclHelper<true> (this=0x7fffffffca30, pnodeFnc=0x7ff7f16a5800, pNameHint=0x0, flags=16, pHasName=0x7fffffff9adf, fUnaryOrParen=false, noStmtContext=false, pNeedScanRCurly=0x7fffffff9ab2, 
    skipFormals=false) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:5147
5147	            AssertMsg(!fLambda, "Deferring function parsing of a function does not handle lambda syntax");
(gdb) bt
#0  0x00007ffff5ce855a in Parser::ParseFncDeclHelper<true> (this=0x7fffffffca30, pnodeFnc=0x7ff7f16a5800, pNameHint=0x0, flags=16, pHasName=0x7fffffff9adf, fUnaryOrParen=false, noStmtContext=false, pNeedScanRCurly=0x7fffffff9ab2, 
    skipFormals=false) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:5147
#1  0x00007ffff5cdfe80 in Parser::ParseFncDecl<true> (this=0x7fffffffca30, flags=16, pNameHint=0x0, needsPIDOnRCurlyScan=false, resetParsingSuperRestrictionState=false, fUnaryOrParen=false)
    at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:4621
#2  0x00007ffff5ce3e9a in Parser::ParseExpr<true> (this=0x7fffffffca30, oplMin=0, pfCanAssign=0x0, fAllowIn=1, fAllowEllipsis=0, pNameHint=0x55555591ce1a u"m", pHintLength=0x0, pShortNameOffset=0x0, pToken=0x0, 
    fUnaryOrParen=false, pfLikelyPattern=0x0) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:8421
#3  0x00007ffff5cdecc1 in Parser::ParseStatement<true> (this=0x7fffffffca30) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:10209
#4  0x00007ffff5cc7aa7 in Parser::ParseStmtList<true> (this=0x7fffffffca30, ppnodeList=0x7ff7f16a5278, pppnodeLast=0x7fffffffa860, smEnvironment=Parser::SM_OnFunctionCode, isSourceElementList=true, strictModeOn=0x0)
    at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:10478
#5  0x00007ffff5cb76d9 in Parser::FinishFncDecl (this=0x7fffffffca30, pnodeFnc=0x7ff7f16a5210, pNameHint=0x0, lastNodeRef=0x0, skipCurlyBraces=false) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:6858
#6  0x00007ffff5ce8b87 in Parser::ParseFncDeclHelper<true> (this=0x7fffffffca30, pnodeFnc=0x7ff7f16a5210, pNameHint=0x0, flags=0, pHasName=0x7fffffffad9f, fUnaryOrParen=true, noStmtContext=false, pNeedScanRCurly=0x7fffffffad72, 
    skipFormals=false) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:5274
#7  0x00007ffff5cdfe80 in Parser::ParseFncDecl<true> (this=0x7fffffffca30, flags=0, pNameHint=0x0, needsPIDOnRCurlyScan=false, resetParsingSuperRestrictionState=true, fUnaryOrParen=true)
    at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:4621
#8  0x00007ffff5cf0b74 in Parser::ParseTerm<true> (this=0x7fffffffca30, fAllowCall=1, pNameHint=0x0, pHintLength=0x7fffffffb2e4, pShortNameOffset=0x7fffffffb2e0, pToken=0x7fffffffb320, fUnaryOrParen=true, 
    pfCanAssign=0x7fffffffb33c, pfLikelyPattern=0x7fffffffb284, pfIsDotOrIndex=0x7fffffffb33a) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:3165
#9  0x00007ffff5ce346f in Parser::ParseExpr<true> (this=0x7fffffffca30, oplMin=0, pfCanAssign=0x7fffffffb570, fAllowIn=1, fAllowEllipsis=0, pNameHint=0x0, pHintLength=0x0, pShortNameOffset=0x0, pToken=0x7fffffffb578, 
    fUnaryOrParen=true, pfLikelyPattern=0x0) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:8211
#10 0x00007ffff5cf02cb in Parser::ParseTerm<true> (this=0x7fffffffca30, fAllowCall=1, pNameHint=0x0, pHintLength=0x7fffffffb894, pShortNameOffset=0x7fffffffb890, pToken=0x7fffffffb8d0, fUnaryOrParen=false, 
    pfCanAssign=0x7fffffffb8ec, pfLikelyPattern=0x7fffffffb834, pfIsDotOrIndex=0x7fffffffb8ea) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:2953
#11 0x00007ffff5ce346f in Parser::ParseExpr<true> (this=0x7fffffffca30, oplMin=0, pfCanAssign=0x0, fAllowIn=1, fAllowEllipsis=0, pNameHint=0x0, pHintLength=0x0, pShortNameOffset=0x0, pToken=0x0, fUnaryOrParen=false, 
    pfLikelyPattern=0x0) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:8211
#12 0x00007ffff5cdecc1 in Parser::ParseStatement<true> (this=0x7fffffffca30) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:10209
#13 0x00007ffff5cc7aa7 in Parser::ParseStmtList<true> (this=0x7fffffffca30, ppnodeList=0x7ff7f16a5098, pppnodeLast=0x7fffffffc450, smEnvironment=Parser::SM_OnGlobalCode, isSourceElementList=true, strictModeOn=0x0)
    at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:10478
#14 0x00007ffff5ca933b in Parser::Parse (this=0x7fffffffca30, pszSrc=0x5555558b87d0 "(function() {\n    \"use asm\";\n    m => 0;\n})()", offset=0, length=45, charOffset=0, grfscr=4096, lineNumber=0, 
    nextFunctionId=0x7ff7f1f1a284, pse=0x7fffffffd1d0) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:10999
#15 0x00007ffff5ca8553 in Parser::ParseSourceInternal (this=0x7fffffffca30, parseTree=0x7fffffffc848, pszSrc=0x5555558b87d0 "(function() {\n    \"use asm\";\n    m => 0;\n})()", offsetInBytes=0, encodedCharCount=45, 
    offsetInChars=0, fromExternal=true, grfscr=4096, pse=0x7fffffffd1d0, nextFunctionId=0x7ff7f1f1a284, lineNumber=0, sourceContextInfo=0x7ff7f1f1a280) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:378
#16 0x00007ffff5cba419 in Parser::ParseUtf8Source (this=0x7fffffffca30, parseTree=0x7fffffffc848, pSrc=0x5555558b87d0 "(function() {\n    \"use asm\";\n    m => 0;\n})()", length=45, grfsrc=4096, pse=0x7fffffffd1d0, 
    nextFunctionId=0x7ff7f1f1a284, sourceContextInfo=0x7ff7f1f1a280) at /home/skywinlinvm/chakracore/lib/Parser/Parse.cpp:11188
#17 0x00007ffff51a4e2f in Js::ScriptContext::ParseScript (this=0x55555590b450, parser=0x7fffffffca30, script=0x5555558b87d0 "(function() {\n    \"use asm\";\n    m => 0;\n})()", cb=45, pSrcInfo=0x7fffffffce90, pse=0x7fffffffd1d0, 
    ppSourceInfo=0x7fffffffce88, rootDisplayName=0x7ffff5e8d2f0 <Js::Constants::GlobalCode> u"Global code", loadScriptFlag=(LoadScriptFlag_Utf8Source | LoadScriptFlag_ExternalArrayBuffer), sourceIndex=0x7fffffffca2c, 
    scriptSource=0x7ff7f1f30050) at /home/skywinlinvm/chakracore/lib/Runtime/Base/ScriptContext.cpp:1846
#18 0x00007ffff51a539b in Js::ScriptContext::LoadScript (this=0x55555590b450, script=0x5555558b87d0 "(function() {\n    \"use asm\";\n    m => 0;\n})()", cb=45, pSrcInfo=0x7fffffffce90, pse=0x7fffffffd1d0, 
    ppSourceInfo=0x7fffffffce88, rootDisplayName=0x7ffff5e8d2f0 <Js::Constants::GlobalCode> u"Global code", loadScriptFlag=(LoadScriptFlag_Utf8Source | LoadScriptFlag_ExternalArrayBuffer), scriptSource=0x7ff7f1f30050)
    at /home/skywinlinvm/chakracore/lib/Runtime/Base/ScriptContext.cpp:1891
#19 0x00007ffff4bd02d5 in RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73::operator()(Js::ScriptContext*, TTD::TTDJsRTActionResultAutoRecorder&) const (this=0x7fffffffd0d0, scriptContext=0x55555590b450, _actionEntryPopper=...) at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:2928
#20 0x00007ffff4bcffc7 in _JsErrorCode ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool)::{lambda(Js::ScriptContext*)#1}::operator()(Js::ScriptContext*) const (this=0x7fffffffd058, scriptContext=0x55555590b450) at /home/skywinlinvm/chakracore/lib/Jsrt/JsrtInternal.h:293
#21 0x00007ffff4bcf8cd in ContextAPINoScriptWrapper_Core<_JsErrorCode ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool)::{lambda(Js::ScriptContext*)#1}>(_JsErrorCode ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool)::{lambda(Js::ScriptContext*)#1}, bool, bool) (fn=..., 
    allowInObjectBeforeCollectCallback=false, scriptExceptionAllowed=false) at /home/skywinlinvm/chakracore/lib/Jsrt/JsrtInternal.h:254
#22 0x00007ffff4ba47d8 in ContextAPINoScriptWrapper<RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_73, bool, bool) (fn=..., allowInObjectBeforeCollectCallback=false, 
    scriptExceptionAllowed=false) at /home/skywinlinvm/chakracore/lib/Jsrt/JsrtInternal.h:291
#23 0x00007ffff4ba4689 in RunScriptCore (scriptSource=0x7ff7f1f30050, script=0x5555558b87d0 "(function() {\n    \"use asm\";\n    m => 0;\n})()", cb=45, 
    loadScriptFlag=(LoadScriptFlag_Utf8Source | LoadScriptFlag_ExternalArrayBuffer), sourceContext=0, sourceUrl=0x7ff7f16a0000 u"/home/skywinlinvm/testchakracore/1case.js", parseOnly=false, 
    parseAttributes=JsParseScriptAttributeNone, isSourceModule=false, result=0x0) at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:2877
#24 0x00007ffff4ba72ce in CompileRun (scriptVal=0x7ff7f1f30050, sourceContext=0, sourceUrl=0x7ff7f1f09020, parseAttributes=JsParseScriptAttributeNone, result=0x0, parseOnly=false)
    at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:4336
#25 JsRun (scriptVal=0x7ff7f1f30050, sourceContext=0, sourceUrl=0x7ff7f1f09020, parseAttributes=JsParseScriptAttributeNone, result=0x0) at /home/skywinlinvm/chakracore/lib/Jsrt/Jsrt.cpp:4358
#26 0x000055555555eafe in ChakraRTInterface::JsRun (script=0x7ff7f1f30050, sourceContext=0, sourceUrl=0x7ff7f1f09020, parseAttributes=JsParseScriptAttributeNone, result=0x0)
    at /home/skywinlinvm/chakracore/bin/ch/ChakraRtInterface.h:367
#27 0x000055555555ca92 in RunScript (fileName=0x5555558d5e90 "1case.js", fileContents=0x5555558b87d0 "(function() {\n    \"use asm\";\n    m => 0;\n})()", bufferValue=0x0, 
    fullPath=0x7fffffffd9c0 "/home/skywinlinvm/testchakracore/1case.js") at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:321
#28 0x000055555555deb0 in ExecuteTest (fileName=0x5555558d5e90 "1case.js") at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:594
#29 0x000055555555dfb0 in ExecuteTestWithMemoryCheck (fileName=0x5555558d5e90 "1case.js") at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:642
#30 0x000055555555e4f0 in main (argc=2, c_argv=0x7fffffffdd38) at /home/skywinlinvm/chakracore/bin/ch/ch.cpp:869
(gdb)
```

**Comment by dilijev** [comment]
@rajatd re: deferred parsing

**Comment by EdMaurer** [comment]
Not something to put in 1.4.1
