### ISSUE TITLE
issue in utf8::DecodeTail

### ISSUE THREAD

**Issue by revskills** [Microsoft/ChakraCore#2336]
```sh
==32522==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000ef15 at pc 0x55e3acdaa1a6 bp 0x7ffd2be5b780 sp 0x7ffd2be5b778
READ of size 1 at 0x60200000ef15 thread T0
    #0 0x55e3acdaa1a5 in utf8::DecodeTail(char16_t, unsigned char const*&, unsigned char const*, utf8::DecodeOptions&) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x4d61a5)
    #1 0x55e3acda7c67 in utf8::DecodeInto(char16_t*, unsigned char const*, unsigned long, utf8::DecodeOptions) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x4d3c67)
    #2 0x55e3add51ee8 in Scanner<UTF8EncodingPolicyBase<false> >::SysAllocErrorLine(int, char16_t**) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x147dee8)
    #3 0x55e3adda4a96 in CompileScriptException::ProcessError(IScanner*, int, ParseNode*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x14d0a96)
    #4 0x55e3adb7d364 in Parser::ParseSourceInternal(ParseNode**, unsigned char const*, unsigned long, unsigned long, unsigned int, bool, unsigned int, CompileScriptException*, unsigned int*, unsigned int, SourceContextInfo*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x12a9364)
    #5 0x55e3adb9e44a in Parser::ParseUtf8Source(ParseNode**, unsigned char const*, unsigned long, unsigned int, CompileScriptException*, unsigned int*, SourceContextInfo*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x12ca44a)
    #6 0x55e3acea3838 in Js::ScriptContext::ParseScript(Parser*, unsigned char const*, unsigned long, SRCINFO const*, CompileScriptException*, Js::Utf8SourceInfo**, char16_t const*, LoadScriptFlag, unsigned int*, void*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x5cf838)
    #7 0x55e3acea42d2 in Js::ScriptContext::LoadScript(unsigned char const*, unsigned long, SRCINFO const*, CompileScriptException*, Js::Utf8SourceInfo**, char16_t const*, LoadScriptFlag, void*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x5d02d2)
    #8 0x55e3acd5d178 in RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x489178)
    #9 0x55e3acd66d8d in JsRun (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x492d8d)
    #10 0x55e3acc10b01 in RunScript(char const*, char const*, void*, char*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x33cb01)
    #11 0x55e3acc1256c in ExecuteTest(char const*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x33e56c)
    #12 0x55e3acc12e1e in main (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x33ee1e)
    #13 0x7f146012682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x55e3acb3b7a8 in _start (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x2677a8)

0x60200000ef15 is located 0 bytes to the right of 5-byte region [0x60200000ef10,0x60200000ef15)
allocated by thread T0 here:
    #0 0x55e3acbdb908 in __interceptor_malloc (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x307908)
    #1 0x55e3acc19648 in Helpers::LoadScriptFromFile(char const*, char const*&, unsigned int*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x345648)
    #2 0x55e3acc11bfc in ExecuteTest(char const*) (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x33dbfc)
    #3 0x55e3acc12e1e in main (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x33ee1e)
    #4 0x7f146012682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/fuzzer/browsers/ChakraCore/BuildLinux/Release/ch+0x4d61a5) in utf8::DecodeTail(char16_t, unsigned char const*&, unsigned char const*, utf8::DecodeOptions&)
Shadow bytes around the buggy address:
  0x0c047fff9d90: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff9da0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff9db0: fa fa fd fd fa fa 04 fa fa fa fd fd fa fa fd fd
  0x0c047fff9dc0: fa fa 04 fa fa fa 00 fa fa fa 00 fa fa fa 00 00
  0x0c047fff9dd0: fa fa 04 fa fa fa 00 00 fa fa 04 fa fa fa 01 fa
=>0x0c047fff9de0: fa fa[05]fa fa fa fd fa fa fa fd fa fa fa 00 04
  0x0c047fff9df0: fa fa 00 00 fa fa fd fd fa fa 04 fa fa fa 00 fa
  0x0c047fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9e10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9e20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9e30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==32522==ABORTING

```
Minimized sample:

ff7/Cg==

**Comment by boingoing** [comment]
This looks like the same issue fixed by https://github.com/Microsoft/ChakraCore/pull/2304 in the release/1.4 branch. I tested-out this minimized sample with the binary built from release/1.4 and we no longer read past the end of the source buffer. Thanks for reporting it, I'm going to close this issue.

**Comment by revskills** [comment]
This issue was reported to Microsoft on Jan 2, 7 days ago and after no ticket updates I've reported here #TRK:0901002828
