### ISSUE TITLE
ASAN: TypedArray transfer can leak memory

### ISSUE THREAD

**Issue by Penguinwizzard** [Microsoft/ChakraCore#2733]
Running ASAN on the test/typedarray/transfer.js test reports a memory leak on application exit. The leaked memory is sized exactly the same as the TypedArray in the test. The affected test has been marked as exclude_sanitize_address for now in PR #2730 to allow ASAN CI to be enabled.

**Comment by Penguinwizzard** [comment]
This issue still repros on 759c8ce0c10c13e070a033ddf7cd18a4b61395cb, which includes the linked change; the ASAN report on the failed test is as follows:

```
[1872/1900 0.68] Failed -> typedarray/transfer.js
/home/demorri/ChakraCore_VSO/out/Debug/ch -WERExceptionSupport -ExtendedErrorStackForTestHost -BaselineMode -maxInterpretCount:1 -maxSimpleJitRunCount:1 -bgjit- -dynamicprofilecache:profile.dpl.3373 -ArrayBufferTransfer /home/demorri/ChakraCore_VSO/test/typedarray/transfer.js

Output:
----------------------------
0
4194304
43
42
44
0
1048576
undefined
42
0
80
42
0
0
0
2097152
0
0

=================================================================
==17302==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2097152 byte(s) in 1 object(s) allocated from:
    #0 0x7f9d79f367f8 in __interceptor_malloc (/home/demorri/ChakraCore_VSO/out/Debug/ch+0xc3e7f8)
    #1 0x7f9d79ff3567 in CorUnix::InternalMalloc(unsigned long) /home/demorri/ChakraCore_VSO/pal/src/cruntime/malloc.cpp:114:20
    #2 0x7f9d79ff3534 in PAL_malloc /home/demorri/ChakraCore_VSO/pal/src/cruntime/malloc.cpp:98:12
    #3 0x7f9d7b5b5d8f in Js::ArrayBuffer::ArrayBuffer<void* (*)(unsigned long)>(unsigned int, Js::DynamicType*, void* (*)(unsigned long)) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:599:33
    #4 0x7f9d7b5b079f in Js::JavascriptArrayBuffer::JavascriptArrayBuffer(unsigned int, Js::DynamicType*) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:666:9
    #5 0x7f9d7b5b0b04 in Js::JavascriptArrayBuffer::Create(unsigned int, Js::DynamicType*) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:681:41
    #6 0x7f9d7b7929e4 in Js::JavascriptLibrary::CreateArrayBuffer(unsigned int) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptLibrary.cpp:6178:28
    #7 0x7f9d7b5b1893 in Js::JavascriptArrayBuffer::TransferInternal(unsigned int) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:819:30
    #8 0x7f9d7b5ae925 in Js::ArrayBuffer::EntryTransfer(Js::RecyclableObject*, Js::CallInfo, ...) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:443:16
    #9 0x7f9d7bc1735d in amd64_CallFunction /home/demorri/ChakraCore_VSO/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
    #10 0x7f9d7b748763 in void* Js::JavascriptFunction::CallFunction<true>(Js::RecyclableObject*, void* (*)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:1346:16
    #11 0x7f9d7b3c2d96 in void Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, Js::RecyclableObject*, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3902:50
    #12 0x7f9d7b3c2212 in void Js::InterpreterStackFrame::OP_ProfileCallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, Js::RecyclableObject*, unsigned int, unsigned short, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3926:9
    #13 0x7f9d7b326830 in void Js::InterpreterStackFrame::OP_ProfiledCallIWithICIndex<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, unsigned int) /home/demorri/ChakraCore_VSO/lib/Runtime/./Language/InterpreterStackFrame.h:457:131
    #14 0x7f9d7b039000 in Js::InterpreterStackFrame::ProcessProfiled() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterHandler.inl:86:3
    #15 0x7f9d7af84478 in Js::InterpreterStackFrame::Process() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3452:20
    #16 0x7f9d7af82b53 in Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction*, Js::ArgumentReader, void*, void*, bool) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:2039:27
    #17 0x7f9d7af80bf3 in Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:1775:16
    #18 0x7f9d73a00fa1  (<unknown module>)
    #19 0x7f9d7bc1735d in amd64_CallFunction /home/demorri/ChakraCore_VSO/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
    #20 0x7f9d7b748763 in void* Js::JavascriptFunction::CallFunction<true>(Js::RecyclableObject*, void* (*)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:1346:16
    #21 0x7f9d7b733ff4 in Js::JavascriptFunction::CallRootFunctionInternal(Js::Arguments, Js::ScriptContext*, bool) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:740:20
    #22 0x7f9d7b733b88 in Js::JavascriptFunction::CallRootFunction(Js::Arguments, Js::ScriptContext*, bool) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:688:15
    #23 0x7f9d7a1b88d1 in RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74::operator()(Js::ScriptContext*, TTD::TTDJsRTActionResultAutoRecorder&) const /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:3050:33
    #24 0x7f9d7a1b7c20 in _JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74)::{lambda(Js::ScriptContext*)#1}::operator()(Js::ScriptContext*) const /home/demorri/ChakraCore_VSO/lib/Jsrt/JsrtInternal.h:216:16
    #25 0x7f9d7a1b73ba in _JsErrorCode ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74)::{lambda(Js::ScriptContext*)#1}>(_JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74)::{lambda(Js::ScriptContext*)#1}) /home/demorri/ChakraCore_VSO/lib/Jsrt/JsrtInternal.h:171:23
    #26 0x7f9d7a15d23b in _JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74) /home/demorri/ChakraCore_VSO/lib/Jsrt/JsrtInternal.h:214:27
    #27 0x7f9d7a15cd0b in RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**) /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:3001:12
    #28 0x7f9d7a166871 in CompileRun(void*, unsigned long, void*, _JsParseScriptAttributes, void**, bool) /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:4306:12
    #29 0x7f9d7a166871 in JsRun /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:4328
    #30 0x7f9d79f71192 in ChakraRTInterface::JsRun(void*, unsigned long, void*, _JsParseScriptAttributes, void**) /home/demorri/ChakraCore_VSO/bin/ch/ChakraRtInterface.h:378:179

Direct leak of 80 byte(s) in 1 object(s) allocated from:
    #0 0x7f9d79f36bd0 in __interceptor_realloc (/home/demorri/ChakraCore_VSO/out/Debug/ch+0xc3ebd0)
    #1 0x7f9d79ff3473 in CorUnix::InternalRealloc(void*, unsigned long) /home/demorri/ChakraCore_VSO/pal/src/cruntime/malloc.cpp:67:17
    #2 0x7f9d79ff33bc in PAL_realloc /home/demorri/ChakraCore_VSO/pal/src/cruntime/malloc.cpp:42:12
    #3 0x7f9d7b5b2ca0 in Js::ReallocZero(unsigned char*, unsigned long, unsigned long) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:799:31
    #4 0x7f9d7b5b2467 in Js::JavascriptArrayBuffer::TransferInternal(unsigned int) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:877:33
    #5 0x7f9d7b5ae925 in Js::ArrayBuffer::EntryTransfer(Js::RecyclableObject*, Js::CallInfo, ...) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:443:16
    #6 0x7f9d7bc1735d in amd64_CallFunction /home/demorri/ChakraCore_VSO/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
    #7 0x7f9d7b748763 in void* Js::JavascriptFunction::CallFunction<true>(Js::RecyclableObject*, void* (*)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:1346:16
    #8 0x7f9d7b3c2d96 in void Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, Js::RecyclableObject*, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3902:50
    #9 0x7f9d7b3c2212 in void Js::InterpreterStackFrame::OP_ProfileCallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, Js::RecyclableObject*, unsigned int, unsigned short, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3926:9
    #10 0x7f9d7b326830 in void Js::InterpreterStackFrame::OP_ProfiledCallIWithICIndex<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, unsigned int) /home/demorri/ChakraCore_VSO/lib/Runtime/./Language/InterpreterStackFrame.h:457:131
    #11 0x7f9d7b039000 in Js::InterpreterStackFrame::ProcessProfiled() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterHandler.inl:86:3
    #12 0x7f9d7af84478 in Js::InterpreterStackFrame::Process() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3452:20
    #13 0x7f9d7af82b53 in Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction*, Js::ArgumentReader, void*, void*, bool) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:2039:27
    #14 0x7f9d7af80bf3 in Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:1775:16
    #15 0x7f9d73a00fa1  (<unknown module>)
    #16 0x7f9d7bc1735d in amd64_CallFunction /home/demorri/ChakraCore_VSO/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
    #17 0x7f9d7b748763 in void* Js::JavascriptFunction::CallFunction<true>(Js::RecyclableObject*, void* (*)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:1346:16
    #18 0x7f9d7b733ff4 in Js::JavascriptFunction::CallRootFunctionInternal(Js::Arguments, Js::ScriptContext*, bool) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:740:20
    #19 0x7f9d7b733b88 in Js::JavascriptFunction::CallRootFunction(Js::Arguments, Js::ScriptContext*, bool) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:688:15
    #20 0x7f9d7a1b88d1 in RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74::operator()(Js::ScriptContext*, TTD::TTDJsRTActionResultAutoRecorder&) const /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:3050:33
    #21 0x7f9d7a1b7c20 in _JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74)::{lambda(Js::ScriptContext*)#1}::operator()(Js::ScriptContext*) const /home/demorri/ChakraCore_VSO/lib/Jsrt/JsrtInternal.h:216:16
    #22 0x7f9d7a1b73ba in _JsErrorCode ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74)::{lambda(Js::ScriptContext*)#1}>(_JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74)::{lambda(Js::ScriptContext*)#1}) /home/demorri/ChakraCore_VSO/lib/Jsrt/JsrtInternal.h:171:23
    #23 0x7f9d7a15d23b in _JsErrorCode ContextAPIWrapper<false, RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74>(RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**)::$_74) /home/demorri/ChakraCore_VSO/lib/Jsrt/JsrtInternal.h:214:27
    #24 0x7f9d7a15cd0b in RunScriptCore(void*, unsigned char const*, unsigned long, LoadScriptFlag, unsigned long, char16_t const*, bool, _JsParseScriptAttributes, bool, void**) /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:3001:12
    #25 0x7f9d7a166871 in CompileRun(void*, unsigned long, void*, _JsParseScriptAttributes, void**, bool) /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:4306:12
    #26 0x7f9d7a166871 in JsRun /home/demorri/ChakraCore_VSO/lib/Jsrt/Jsrt.cpp:4328
    #27 0x7f9d79f71192 in ChakraRTInterface::JsRun(void*, unsigned long, void*, _JsParseScriptAttributes, void**) /home/demorri/ChakraCore_VSO/bin/ch/ChakraRtInterface.h:378:179
    #28 0x7f9d79f6ca98 in RunScript(char const*, char const*, void (*)(void*), void*, char*) /home/demorri/ChakraCore_VSO/bin/ch/ch.cpp:450:25
    #29 0x7f9d79f6f21c in ExecuteTest(char const*) /home/demorri/ChakraCore_VSO/bin/ch/ch.cpp:744:13
    #30 0x7f9d79f6f3db in ExecuteTestWithMemoryCheck(char*) /home/demorri/ChakraCore_VSO/bin/ch/ch.cpp:794:10

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f9d79f367f8 in __interceptor_malloc (/home/demorri/ChakraCore_VSO/out/Debug/ch+0xc3e7f8)
    #1 0x7f9d79ff3567 in CorUnix::InternalMalloc(unsigned long) /home/demorri/ChakraCore_VSO/pal/src/cruntime/malloc.cpp:114:20
    #2 0x7f9d79ff3534 in PAL_malloc /home/demorri/ChakraCore_VSO/pal/src/cruntime/malloc.cpp:98:12
    #3 0x7f9d7b5b5d8f in Js::ArrayBuffer::ArrayBuffer<void* (*)(unsigned long)>(unsigned int, Js::DynamicType*, void* (*)(unsigned long)) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:599:33
    #4 0x7f9d7b5b079f in Js::JavascriptArrayBuffer::JavascriptArrayBuffer(unsigned int, Js::DynamicType*) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:666:9
    #5 0x7f9d7b5b0b04 in Js::JavascriptArrayBuffer::Create(unsigned int, Js::DynamicType*) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:681:41
    #6 0x7f9d7b7929e4 in Js::JavascriptLibrary::CreateArrayBuffer(unsigned int) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptLibrary.cpp:6178:28
    #7 0x7f9d7b5acb8a in Js::ArrayBuffer::NewInstance(Js::RecyclableObject*, Js::CallInfo, ...) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/ArrayBuffer.cpp:337:36
    #8 0x7f9d7bc1735d in amd64_CallFunction /home/demorri/ChakraCore_VSO/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
    #9 0x7f9d7b748763 in void* Js::JavascriptFunction::CallFunction<true>(Js::RecyclableObject*, void* (*)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:1346:16
    #10 0x7f9d7b735738 in Js::JavascriptFunction::CallAsConstructor(void*, void*, Js::Arguments, Js::ScriptContext*, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:925:30
    #11 0x7f9d7b42d862 in Js::JavascriptOperators::NewScObject(void*, Js::Arguments, Js::ScriptContext*, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/JavascriptOperators.cpp:6432:36
    #12 0x7f9d7b4e2562 in Js::ProfilingHelpers::ProfiledNewScObject(void*, Js::Arguments, Js::FunctionBody*, unsigned short, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/ProfilingHelpers.cpp:654:26
    #13 0x7f9d7b2e45f0 in Js::InterpreterStackFrame::ProfiledNewScObject_Helper(void*, unsigned short, unsigned short, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:6426:13
    #14 0x7f9d7b3d0af1 in void Js::InterpreterStackFrame::OP_NewScObject_Impl<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> >, true, false>(Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > const*, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:6301:17
    #15 0x7f9d7b32dce5 in void Js::InterpreterStackFrame::OP_ProfiledNewScObject<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*) /home/demorri/ChakraCore_VSO/lib/Runtime/./Language/InterpreterStackFrame.h:691:110
    #16 0x7f9d7b045658 in Js::InterpreterStackFrame::ProcessProfiled() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterHandler.inl:283:3
    #17 0x7f9d7af84478 in Js::InterpreterStackFrame::Process() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3452:20
    #18 0x7f9d7af82b53 in Js::InterpreterStackFrame::InterpreterHelper(Js::ScriptFunction*, Js::ArgumentReader, void*, void*, bool) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:2039:27
    #19 0x7f9d7af80bf3 in Js::InterpreterStackFrame::InterpreterThunk(Js::JavascriptCallStackLayout*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:1775:16
    #20 0x7f9d73a00f69  (<unknown module>)
    #21 0x7f9d7bc1735d in amd64_CallFunction /home/demorri/ChakraCore_VSO/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
    #22 0x7f9d7b748763 in void* Js::JavascriptFunction::CallFunction<true>(Js::RecyclableObject*, void* (*)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments) /home/demorri/ChakraCore_VSO/lib/Runtime/Library/JavascriptFunction.cpp:1346:16
    #23 0x7f9d7b3bfd36 in void Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, Js::RecyclableObject*, unsigned int, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3888:17
    #24 0x7f9d7b3c732f in void Js::InterpreterStackFrame::OP_ProfileReturnTypeCallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, Js::RecyclableObject*, unsigned int, unsigned short, Js::AuxArray<unsigned int> const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3936:9
    #25 0x7f9d7b327816 in void Js::InterpreterStackFrame::OP_ProfiledReturnTypeCallI<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > >(Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallI<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > const*, unsigned int) /home/demorri/ChakraCore_VSO/lib/Runtime/./Language/InterpreterStackFrame.h:462:130
    #26 0x7f9d7b0394d6 in Js::InterpreterStackFrame::ProcessProfiled() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterHandler.inl:91:3
    #27 0x7f9d7af84478 in Js::InterpreterStackFrame::Process() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:3452:20
    #28 0x7f9d7b04f56d in Js::InterpreterStackFrame::OP_TryCatch(Js::OpLayoutBr const*) /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterStackFrame.cpp:6565:17
    #29 0x7f9d7b04bdc2 in Js::InterpreterStackFrame::ProcessProfiled() /home/demorri/ChakraCore_VSO/lib/Runtime/Language/InterpreterHandler.inl:379:3

SUMMARY: AddressSanitizer: 2097248 byte(s) leaked in 3 allocation(s).

----------------------------
exit code: 1
```
