### ISSUE TITLE
Nullptr assertion error/crash in GetOwnPropertyDescriptor with revoked proxy

### ISSUE THREAD

**Issue by anba** [Microsoft/ChakraCore#2823]
Test case:
```js
var {proxy, revoke} = Proxy.revocable({a: 0}, new Proxy({}, {
    get(t, pk) {
        if (pk === "getOwnPropertyDescriptor")
            revoke();
    }
}));
Object.keys(proxy);
```

```gdb
0x00007ffff3b80ba5 in Js::JavascriptOperators::GetOwnPropertyDescriptor (obj=0x0, propertyId=739, scriptContext=0x55555589f288, propertyDescriptor=0x7fffffff89c8)
    at /home/andre/git/ChakraCore/lib/Runtime/Language/JavascriptOperators.cpp:1227
1227	        Assert(obj);
(gdb) bt
#0  0x00007ffff3b80ba5 in Js::JavascriptOperators::GetOwnPropertyDescriptor (obj=0x0, propertyId=739, scriptContext=0x55555589f288, propertyDescriptor=0x7fffffff89c8)
    at /home/andre/git/ChakraCore/lib/Runtime/Language/JavascriptOperators.cpp:1227
#1  0x00007ffff3ea0de6 in Js::JavascriptProxy::GetOwnPropertyDescriptor(Js::RecyclableObject*, int, Js::ScriptContext*, Js::PropertyDescriptor*)::$_16::operator()() const (this=0x7fffffff8800)
    at /home/andre/git/ChakraCore/lib/Runtime/Library/JavascriptProxy.cpp:1656
#2  0x00007ffff3e9de24 in Js::JavascriptProxy::GetPropertyDescriptorTrap<Js::JavascriptProxy::GetOwnPropertyDescriptor(Js::RecyclableObject*, int, Js::ScriptContext*, Js::PropertyDescriptor*)::$_16, Js::JavascriptProxy::GetOwnPropertyDescriptor(Js::RecyclableObject*, int, Js::ScriptContext*, Js::PropertyDescriptor*)::$_17>(void*, Js::JavascriptProxy::GetOwnPropertyDescriptor(Js::RecyclableObject*, int, Js::ScriptContext*, Js::PropertyDescriptor*)::$_16, Js::JavascriptProxy::GetOwnPropertyDescriptor(Js::RecyclableObject*, int, Js::ScriptContext*, Js::PropertyDescriptor*)::$_17, Js::PropertyDescriptor*, Js::ScriptContext*) (this=0x7ffff0b84870, originalInstance=0x7ffff0b84870, fn=..., getPropertyId=..., resultDescriptor=0x7fffffff89c8, requestContext=0x55555589f288)
    at /home/andre/git/ChakraCore/lib/Runtime/Library/JavascriptProxy.cpp:218
#3  0x00007ffff3e96e99 in Js::JavascriptProxy::GetOwnPropertyDescriptor (obj=0x7ffff0b84870, propertyId=739, scriptContext=0x55555589f288, propertyDescriptor=0x7fffffff89c8)
    at /home/andre/git/ChakraCore/lib/Runtime/Library/JavascriptProxy.cpp:1659
#4  0x00007ffff3b80d3d in Js::JavascriptOperators::GetOwnPropertyDescriptor (obj=0x7ffff0b84870, propertyId=739, scriptContext=0x55555589f288, propertyDescriptor=0x7fffffff89c8)
    at /home/andre/git/ChakraCore/lib/Runtime/Language/JavascriptOperators.cpp:1233
#5  0x00007ffff3b81332 in Js::JavascriptOperators::GetOwnEnumerablePropertyNames (instance=0x7ffff0b84870, scriptContext=0x55555589f288)
    at /home/andre/git/ChakraCore/lib/Runtime/Language/JavascriptOperators.cpp:1175
#6  0x00007ffff3e7336e in Js::JavascriptObject::EntryKeys (function=0x7ffff033f480, callInfo=...)
    at /home/andre/git/ChakraCore/lib/Runtime/Library/JavascriptObject.cpp:10
....
```

**Comment by akroshg** [comment]
@anba thanks for reporting this.
