### ISSUE TITLE
Failed assertion at lib/Common/Memory/HeapBlock.cpp

### ISSUE THREAD

**Issue by gaa-cifasis** [Microsoft/ChakraCore#3280]
Hi,

We found an failed assertion in the ChakraCore interpreter (ch) when you run the following test case: 

```
foo.prototype = new Array(1
                         ,2
                         ,3);
function foo() {
}
var f = new foo();
f.length /= null;
var callCnt = 0;
function cb() {
   callCnt++;
}
var i = f.forEach(cb);
assert.sameValue(callCnt
                ,0
                ,"callCnt");
```

It was tested in Ubuntu 16.04 using the last git revision (52dfe7bc146b70b326ed6e9f521bffa9f902bb2b). To reproduce:

```
$ gdb --args ./ch test.js 
...
ASSERTION 19837: (/home/g/repos/ChakraCore/lib/Common/Memory/HeapBlock.cpp, line 1363) (ObjectInfo(objectIndex) & NewTrackBit) == 0
 Failure: ((ObjectInfo(objectIndex) & NewTrackBit) == 0)

Thread 1 "ch" received signal SIGILL, Illegal instruction.
0x00005555565a48dd in Memory::SmallHeapBlockT<SmallAllocationBlockAttributes>::SweepObjects<(Memory::SweepMode)0> (this=0x61a00015bc30, 
    recycler=0x633000000858) at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBlock.cpp:1363
1363	            Assert((ObjectInfo(objectIndex) & NewTrackBit) == 0);
(gdb) bt
#0  0x00005555565a48dd in Memory::SmallHeapBlockT<SmallAllocationBlockAttributes>::SweepObjects<(Memory::SweepMode)0> (this=0x61a00015bc30, 
    recycler=0x633000000858) at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBlock.cpp:1363
#1  0x00005555565a237b in Memory::SmallHeapBlockT<SmallAllocationBlockAttributes>::Sweep (this=0x61a00015bc30, recyclerSweep=..., 
    queuePendingSweep=false, allocable=true, finalizeCount=341, hasPendingDispose=false)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBlock.cpp:1276
#2  0x00005555567a04ee in Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>::Sweep (this=0x61a00015bc30, recyclerSweep=..., 
    queuePendingSweep=false, allocable=true) at /home/g/repos/ChakraCore/lib/Common/Memory/SmallFinalizableHeapBlock.cpp:268
#3  0x0000555556645908 in Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepHeapBlockList(Memory::RecyclerSweep&, Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*, bool)::{lambda(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*)#1}::operator()(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*) const (this=0x7fffffff2340, heapBlock=0x61a00015bc30)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBucket.cpp:977
#4  0x0000555556645788 in Memory::HeapBlockList::ForEachEditing<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>, Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepHeapBlockList(Memory::RecyclerSweep&, Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*, bool)::{lambda(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*)#1}>(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*, Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>, Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepHeapBlockList(Memory::RecyclerSweep&, Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*, bool)::{lambda(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*)#1}) (list=0x61a00015bc30, tail=0x0, fn=...)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBlock.h:811
#5  0x00005555565fc0e3 in Memory::HeapBlockList::ForEachEditing<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>, Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepHeapBlockList(Memory::RecyclerSweep&, Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*, bool)::{lambda(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*)#1}>(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*, Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepHeapBlockList(Memory::RecyclerSweep&, Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*, bool)::{lambda(Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes>*)#1}) (list=0x61a00015bc30, fn=...) at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBlock.h:801
#6  0x00005555565fb86b in Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepHeapBlockList (
    this=0x633000006328, recyclerSweep=..., heapBlockList=0x61a00015bc30, allocable=true)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBucket.cpp:972
#7  0x00005555565fb1c2 in Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepBucket (this=0x633000006328, 
    recyclerSweep=...) at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBucket.cpp:1147
#8  0x00005555567ade72 in Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SweepBucket<Memory::SmallFinalizableHeapBucketBaseT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::Sweep(Memory::RecyclerSweep&)::{lambda(Memory::RecyclerSweep&)#1}>(Memory::RecyclerSweep&, Memory::SmallFinalizableHeapBucketBaseT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::Sweep(Memory::RecyclerSweep&)::{lambda(Memory::RecyclerSweep&)#1}) (this=0x633000006328, recyclerSweep=..., sweepFn=...)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBucket.h:310
#9  0x00005555567adc9d in Memory::SmallFinalizableHeapBucketBaseT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::Sweep (
    this=0x633000006328, recyclerSweep=...) at /home/g/repos/ChakraCore/lib/Common/Memory/SmallFinalizableHeapBucket.cpp:110
#10 0x00005555565de85e in Memory::HeapBucketGroup<SmallAllocationBlockAttributes>::SweepFinalizableObjects (this=0x6330000061a8, recyclerSweep=...)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBucket.cpp:1653
#11 0x0000555556672303 in Memory::HeapInfo::SweepBuckets (this=0x633000005910, recyclerSweep=..., concurrent=true)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapInfo.cpp:865
#12 0x000055555667281a in Memory::HeapInfo::Sweep (this=0x633000005910, recyclerSweep=..., concurrent=true)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapInfo.cpp:945
#13 0x0000555556723361 in Memory::Recycler::SweepHeap (this=0x633000000858, concurrent=true, recyclerSweep=...)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3187
#14 0x0000555556722ae6 in Memory::Recycler::Sweep (this=0x633000000858, rescanRootBytes=50680, concurrent=true, adjustPartialHeuristics=true)
---Type <return> to continue, or q <return> to quit---
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3019
#15 0x000055555672abbe in Memory::Recycler::PartialCollect (this=0x633000000858, concurrent=true)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:4068
#16 0x0000555556729071 in Memory::Recycler::DoCollect (this=0x633000000858, flags=Memory::CollectOnAllocation)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3885
#17 0x0000555556706fe7 in Memory::DefaultRecyclerCollectionWrapper::ExecuteRecyclerCollectionFunction (this=0x62300000e158, recycler=0x633000000858, 
    function=
    (BOOL (Memory::Recycler::*)(Memory::Recycler * const, Memory::CollectionFlags)) 0x555556727af0 <Memory::Recycler::DoCollect(Memory::CollectionFlags)>, flags=Memory::CollectOnAllocation) at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:94
#18 0x0000555556a0686b in ThreadContext::ExecuteRecyclerCollectionFunctionCommon (this=0x62300000e158, recycler=0x633000000858, function=
    (BOOL (Memory::Recycler::*)(Memory::Recycler * const, Memory::CollectionFlags)) 0x555556727af0 <Memory::Recycler::DoCollect(Memory::CollectionFlags)>, flags=Memory::CollectOnAllocation) at /home/g/repos/ChakraCore/lib/Runtime/Base/ThreadContext.cpp:1941
#19 0x0000555556a08b2e in ThreadContext::ExecuteRecyclerCollectionFunction (this=0x62300000e158, recycler=0x633000000858, function=
    (BOOL (Memory::Recycler::*)(Memory::Recycler * const, Memory::CollectionFlags)) 0x555556727af0 <Memory::Recycler::DoCollect(Memory::CollectionFlags)>, flags=Memory::CollectOnAllocation) at /home/g/repos/ChakraCore/lib/Runtime/Base/ThreadContext.cpp:2140
#20 0x00005555567279a2 in Memory::Recycler::DoCollectWrapped (this=0x633000000858, flags=Memory::CollectOnAllocation)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3737
#21 0x000055555675f643 in Memory::Recycler::Collect<(Memory::CollectionFlags)404819971> (this=0x633000000858)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3697
#22 0x000055555675eed6 in Memory::Recycler::CollectWithHeuristic<(Memory::CollectionFlags)404819971> (this=0x633000000858)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3620
#23 0x00005555567525e3 in Memory::Recycler::CollectInternal<(Memory::CollectionFlags)404819971> (this=0x633000000858)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3579
#24 0x0000555556749c45 in Memory::Recycler::CollectNow<(Memory::CollectionFlags)404819971> (this=0x633000000858)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.cpp:3507
#25 0x00005555565f7129 in Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::SnailAlloc (this=0x633000006328, 
    recycler=0x633000000858, allocator=0x633000006358, sizeCat=48, size=42, attributes=420, nothrow=false)
    at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBucket.cpp:584
#26 0x0000555556a41ced in Memory::HeapBucketT<Memory::SmallFinalizableHeapBlockT<SmallAllocationBlockAttributes> >::RealAlloc<(Memory::ObjectInfoBits)420, false> (this=0x633000006328, recycler=0x633000000858, sizeCat=48, size=42) at /home/g/repos/ChakraCore/lib/Common/Memory/HeapBucket.inl:19
#27 0x0000555556a41b0d in Memory::HeapInfo::RealAlloc<(Memory::ObjectInfoBits)420, false> (this=0x633000005910, recycler=0x633000000858, sizeCat=48, 
    size=42) at /home/g/repos/ChakraCore/lib/Common/Memory/HeapInfo.h:504
#28 0x0000555556a4144e in Memory::Recycler::RealAllocFromBucket<(Memory::ObjectInfoBits)420, true, false> (this=0x633000000858, heap=0x633000005910, 
    size=42) at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.inl:320
#29 0x0000555556a4124e in Memory::Recycler::RealAlloc<(Memory::ObjectInfoBits)420, false> (this=0x633000000858, heap=0x633000005910, size=42)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.inl:395
#30 0x0000555556a40f35 in Memory::Recycler::AllocWithAttributesInlined<(Memory::ObjectInfoBits)164, false> (this=0x633000000858, size=42)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.inl:101
#31 0x0000555556a405dd in Memory::Recycler::AllocWithAttributes<(Memory::ObjectInfoBits)164, false> (this=0x633000000858, size=42)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.h:1466
#32 0x0000555556a30cad in Memory::Recycler::AllocFinalizedLeaf (this=0x633000000858, size=42)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Recycler.h:1269
#33 0x00005555564bef0d in operator new<Memory::Recycler> (byteSize=24, alloc=0x633000000858, AllocFunc=
    (char *(Memory::Recycler::*)(Memory::Recycler * const, size_t)) 0x555556a30c90 <Memory::Recycler::AllocFinalizedLeaf(unsigned long)>, plusSize=18)
    at /home/g/repos/ChakraCore/lib/Common/Memory/Allocator.h:513
---Type <return> to continue, or q <return> to quit---
#34 0x00005555569fe844 in ThreadContext::UncheckedAddPropertyId (this=0x62300000e158, propertyName=..., bind=false, isSymbol=false)
    at /home/g/repos/ChakraCore/lib/Runtime/Base/ThreadContext.cpp:1057
#35 0x0000555556a01109 in ThreadContext::GetOrAddPropertyRecordImpl (this=0x62300000e158, propertyName=..., bind=false)
    at /home/g/repos/ChakraCore/lib/Runtime/Base/ThreadContext.cpp:1228
#36 0x0000555556a3167f in ThreadContext::GetOrAddPropertyRecord (this=0x62300000e158, propertyName=...)
    at /home/g/repos/ChakraCore/lib/Runtime/./Base/ThreadContext.h:1131
#37 0x0000555556a00ed5 in ThreadContext::GetOrAddPropertyId (this=0x62300000e158, propertyName=..., propRecord=0x7fffffff5600)
    at /home/g/repos/ChakraCore/lib/Runtime/Base/ThreadContext.cpp:1213
#38 0x0000555556a00d6b in ThreadContext::GetOrAddPropertyId (this=0x62300000e158, propertyName=0x7fffffff54c0 u"476023", propertyNameLength=6, 
    propertyRecord=0x7fffffff5600) at /home/g/repos/ChakraCore/lib/Runtime/Base/ThreadContext.cpp:1207
#39 0x0000555556913b71 in Js::ScriptContext::GetOrAddPropertyRecord (this=0x62200001c958, propertyName=0x7fffffff54c0 u"476023", 
    propertyNameLength=6, propertyRecord=0x7fffffff5600) at /home/g/repos/ChakraCore/lib/Runtime/Base/ScriptContext.cpp:854
#40 0x0000555557698028 in Js::JavascriptOperators::GetPropertyIdForInt (value=476023, scriptContext=0x62200001c958, propertyRecord=0x7fffffff5600)
    at /home/g/repos/ChakraCore/lib/Runtime/Language/JavascriptOperators.cpp:8537
#41 0x00005555578c22e6 in Js::JavascriptArray::TemplatedGetItem<Js::RecyclableObject> (obj=0x7ffff27800f0, index=476023, element=0x7fffffff57c0, 
    scriptContext=0x62200001c958, checkHasItem=true) at /home/g/repos/ChakraCore/lib/Runtime/Library/JavascriptArray.cpp:3937
#42 0x0000555557957f67 in Js::JavascriptArray::TryTemplatedGetItem<Js::RecyclableObject, unsigned long> (arr=0x7ffff27800f0, index=476023, 
    element=0x7fffffff57c0, scriptContext=0x62200001c958, checkHasItem=true)
    at /home/g/repos/ChakraCore/lib/Runtime/./Library/JavascriptArray.h:634
#43 0x00005555578e6231 in Js::JavascriptArray::TemplatedForEachItemInRange<true, Js::RecyclableObject, unsigned long, Js::JavascriptArray::EntryForEach(Js::RecyclableObject*, Js::CallInfo, ...)::$_8>(Js::RecyclableObject*, unsigned long, unsigned long, Js::ScriptContext*, Js::JavascriptArray::EntryForEach(Js::RecyclableObject*, Js::CallInfo, ...)::$_8) (arr=0x7ffff27800f0, startIndex=0, limitIndex=9007199254740991, scriptContext=0x62200001c958, 
    fn=...) at /home/g/repos/ChakraCore/lib/Runtime/./Library/JavascriptArray.h:669
#44 0x00005555578e55fa in Js::JavascriptArray::EntryForEach (function=0x7ffff0744fc0, callInfo=...)
    at /home/g/repos/ChakraCore/lib/Runtime/Library/JavascriptArray.cpp:8759
#45 0x0000555557ea102e in amd64_CallFunction () at /home/g/repos/ChakraCore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#46 0x00005555579ce314 in Js::JavascriptFunction::CallFunction<true> (function=0x7ffff0744fc0, 
    entryPoint=0x5555578e40f0 <Js::JavascriptArray::EntryForEach(Js::RecyclableObject*, Js::CallInfo, ...)>, args=...)
    at /home/g/repos/ChakraCore/lib/Runtime/Library/JavascriptFunction.cpp:1353
#47 0x00005555576441e7 in Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffad80, playout=0x7ffff07200a4, function=0x7ffff0744fc0, flags=2, spreadIndices=0x0)
    at /home/g/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3904
#48 0x0000555557643663 in Js::InterpreterStackFrame::OP_ProfileCallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffad80, playout=0x7ffff07200a4, function=0x7ffff0744fc0, flags=0, profileId=2, inlineCacheIndex=3, 
    spreadIndices=0x0) at /home/g/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3928
#49 0x00005555575a6321 in Js::InterpreterStackFrame::OP_ProfiledCallIWithICIndex<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > (this=0x7fffffffad80, playout=0x7ffff07200a4, flags=0) at /home/g/repos/ChakraCore/lib/Runtime/./Language/InterpreterStackFrame.h:460
#50 0x00005555572b75a1 in Js::InterpreterStackFrame::ProcessProfiled (this=0x7fffffffad80)
    at /home/g/repos/ChakraCore/lib/Runtime/Language/InterpreterHandler.inl:86
#51 0x0000555557202aa9 in Js::InterpreterStackFrame::Process (this=0x7fffffffad80)
    at /home/g/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3454
#52 0x0000555557201184 in Js::InterpreterStackFrame::InterpreterHelper (function=0x7ffff272c240, args=..., returnAddress=0x7ffff0700fa2, 
    addressOfReturnAddress=0x7fffffffb948, isAsmJs=false) at /home/g/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:2054
#53 0x00005555571ff224 in Js::InterpreterStackFrame::InterpreterThunk (layout=0x7fffffffb960)
    at /home/g/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:1789
---Type <return> to continue, or q <return> to quit---
#54 0x00007ffff0700fa2 in ?? ()
#55 0x00007fffffffb970 in ?? ()
#56 0x0000555557ea102e in amd64_CallFunction () at /home/g/repos/ChakraCore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
Backtrace stopped: frame did not save the PC
```

This issue was found using QuickFuzz.

Regards,
Gustavo.

**Comment by digitalinfinity** [comment]
@jianchun fwiw, I ran this test case overnight on Windows on x64 debug and it didn't seem to assert (didn't terminate either 😄) - this assert is very strange, not sure what is xplat specific that would cause this.

**Comment by jianchun** [comment]
@digitalinfinity Thanks for looking. I tried the repro. It seems to me ChakraCore's huge loop behavior conforms to spec:

```
let obj = {0: '0', 1: '1', length: Infinity};
Array.prototype.forEach.call(obj, console.log);
```

“node” does nothing and immediately exits.
“ch” prints items at 0, 1 and honors the `Infinity` length (loop (2^53 - 1)).

**Comment by jianchun** [comment]
@gaa-cifasis Thanks for reporting this issue and sorry for fixing it this late.

**Comment by gaa-cifasis** [comment]
No problem!
