### ISSUE TITLE
Failed assertion at lib/Runtime/Base/FunctionBody.h

### ISSUE THREAD

**Issue by gaa-cifasis** [Microsoft/ChakraCore#3285]
Hi,

We found an failed assertion in the ChakraCore interpreter (ch) when you run the following test case: 

```
function foo() {
   var x = "bp A";
   x;
   x = "Hit loc B";
   x;
   x = "bp C, BUG";
   x;
   x = "bp D, BUG";
   x;
   x = "bp D";
   x;
}
WScript.Attach(foo);
WScript.Detach(foo);
WScript.Attach(foo);
WScript.Echo("pass");
```

It was tested in Ubuntu 16.04 using the last git revision (52dfe7bc146b70b326ed6e9f521bffa9f902bb2b). To reproduce:

```
$ gdb --args ./ch test.js 
...
0x00005555568a6b2a in Js::EntryPointInfo::GetNativeThrowSpanSequence (this=0x7ffff0624420)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/./Base/FunctionBody.h:874
874	            Assert(this->GetState() != CleanedUp);
(gdb) bt
#0  0x00005555568a6b2a in Js::EntryPointInfo::GetNativeThrowSpanSequence (this=0x7ffff0624420)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/./Base/FunctionBody.h:874
#1  0x0000555556840c9e in Js::FunctionBody::RecordNativeThrowMap (this=0x7ffff077dc00, iter=..., nativeOffset=932, statementIndex=10, 
    entryPoint=0x7ffff0624420, loopNum=4294967295) at /home/gustavo/repos/ChakraCore/lib/Runtime/Base/FunctionBody.cpp:1333
#2  0x0000555558b585f1 in Encoder::Encode (this=0x7ff7ebffc660) at /home/gustavo/repos/ChakraCore/lib/Backend/Encoder.cpp:316
#3  0x0000555558beb453 in Func::TryCodegen (this=0x7ff7ebffcd00) at /home/gustavo/repos/ChakraCore/lib/Backend/Func.cpp:523
#4  0x0000555558be9acf in Func::Codegen (alloc=0x7ff7ebffd700, workItem=0x7ffff05b1030, threadContextInfo=0x62300000e178, 
    scriptContextInfo=0x62200001b158, outputData=0x7ff7ebffd610, epInfo=0x7ffff0624420, runtimeInfo=0x0, 
    polymorphicInlineCacheInfo=0x7ffff063c640, codeGenAllocators=0x61a0000198d8, codeGenProfiler=0x0, isBackgroundJIT=true)
    at /home/gustavo/repos/ChakraCore/lib/Backend/Func.cpp:296
#5  0x00005555586a4790 in NativeCodeGenerator::CodeGen (this=0x61300000d458, pageAllocator=0x61500000dcf8, workItem=0x612000009c98, 
    foreground=false) at /home/gustavo/repos/ChakraCore/lib/Backend/NativeCodeGenerator.cpp:953
#6  0x00005555586aab37 in NativeCodeGenerator::Process (this=0x61300000d458, job=0x612000009ca0, threadData=0x61500000dcd8)
    at /home/gustavo/repos/ChakraCore/lib/Backend/NativeCodeGenerator.cpp:1827
#7  0x000055555877b96a in JsUtil::BackgroundJobProcessor::Process (this=0x61300000d998, job=0x612000009ca0, threadData=0x61500000dcd8)
    at /home/gustavo/repos/ChakraCore/lib/Common/Common/Jobs.cpp:986
#8  0x000055555877c421 in JsUtil::BackgroundJobProcessor::Run (this=0x61300000d998, threadData=0x61500000dcd8)
    at /home/gustavo/repos/ChakraCore/lib/Common/Common/Jobs.cpp:1078
#9  0x0000555558775c00 in JsUtil::BackgroundJobProcessor::StaticThreadProc (lpParam=0x61500000dcd8)
    at /home/gustavo/repos/ChakraCore/lib/Common/Common/Jobs.cpp:1254
#10 0x0000555556358d62 in CorUnix::CPalThread::ThreadEntry (pvParam=0x61c00000e080)
    at /home/gustavo/repos/ChakraCore/pal/src/thread/pal_thread.cpp:1624
#11 0x00007ffff7bc16ba in start_thread (arg=0x7ff7ebfff700) at pthread_create.c:333
#12 0x00007ffff6c383dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Regards,
Gustavo.

**Comment by obastemur** [comment]
This is a duplicate issue of #3352 and #4310 fixes it.
