### ISSUE TITLE
Assertion failed at lib/Runtime/Types/RecyclableObject.inl

### ISSUE THREAD

**Issue by gaa-cifasis** [Microsoft/ChakraCore#3299]
Hi,

We found an failed assertion in the ChakraCore interpreter (ch) when you run the following test case: 

```
WScript = {};
WScript.Echo = console.log;
$ERROR = console.log;
assert = {};
assert.sameValue = function (x
                            ,y
                            ,z) {
       return x == y;
    };
assert.notSameValue =
    function (x,y,z) {
       return not(x == y);
    };
assert.throws = function (x,f) {
       f();
    };
testOption = function (x) {
    };
assert.sameValue(Function.prototype[Symbol.hasInstance].call(0)
                ,false);
assert.sameValue(Function.prototype[Symbol.hasInstance].call({})
                ,false);
```

It was tested in Ubuntu 16.04 using the git revision 52dfe7bc146b70b326ed6e9f521bffa9f902bb2b. To reproduce:

```
$ gdb --args ./ch test.js 
...
ASSERTION 19687: (/home/gustavo/repos/ChakraCore/lib/Jsrt/../Runtime/Types/RecyclableObject.inl, line 29) Ensure instance is a RecyclableObject
 Failure: (Is(aValue))

Thread 1 "ch" received signal SIGILL, Illegal instruction.
0x000055555644937c in Js::RecyclableObject::FromVar (aValue=0x1000000000000)
    at /home/gustavo/repos/ChakraCore/lib/Jsrt/../Runtime/Types/RecyclableObject.inl:29
29	        AssertMsg(Is(aValue), "Ensure instance is a RecyclableObject");
(gdb) bt
#0  0x000055555644937c in Js::RecyclableObject::FromVar (aValue=0x1000000000000)
    at /home/gustavo/repos/ChakraCore/lib/Jsrt/../Runtime/Types/RecyclableObject.inl:29
#1  0x00005555579cafb0 in Js::JavascriptFunction::EntrySymbolHasInstance (function=0x7ffff0744b80, callInfo=...)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Library/JavascriptFunction.cpp:3296
#2  0x0000555557ea102e in amd64_CallFunction () at /home/gustavo/repos/ChakraCore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#3  0x00005555579ce314 in Js::JavascriptFunction::CallFunction<true> (function=0x7ffff0744b80, 
    entryPoint=0x5555579ca8e0 <Js::JavascriptFunction::EntrySymbolHasInstance(Js::RecyclableObject*, Js::CallInfo, ...)>, args=...)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Library/JavascriptFunction.cpp:1353
#4  0x00005555579b92e7 in Js::JavascriptFunction::EntryCall (function=0x7ffff0744a40, callInfo=...)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Library/JavascriptFunction.cpp:649
#5  0x0000555557ea102e in amd64_CallFunction () at /home/gustavo/repos/ChakraCore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#6  0x00005555579ce314 in Js::JavascriptFunction::CallFunction<true> (function=0x7ffff0744a40, 
    entryPoint=0x5555579b8740 <Js::JavascriptFunction::EntryCall(Js::RecyclableObject*, Js::CallInfo, ...)>, args=...)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Library/JavascriptFunction.cpp:1353
#7  0x00005555576441e7 in Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffadc0, playout=0x7ffff07200ac, function=0x7ffff0744a40, flags=2, spreadIndices=0x0)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3904
#8  0x0000555557643663 in Js::InterpreterStackFrame::OP_ProfileCallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffadc0, playout=0x7ffff07200ac, function=0x7ffff0744a40, flags=0, 
    profileId=1, inlineCacheIndex=9, spreadIndices=0x0)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3928
#9  0x00005555575a6321 in Js::InterpreterStackFrame::OP_ProfiledCallIWithICIndex<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > (this=0x7fffffffadc0, playout=0x7ffff07200ac, flags=0)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/./Language/InterpreterStackFrame.h:460
#10 0x00005555572b75a1 in Js::InterpreterStackFrame::ProcessProfiled (this=0x7fffffffadc0)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Language/InterpreterHandler.inl:86
#11 0x0000555557202aa9 in Js::InterpreterStackFrame::Process (this=0x7fffffffadc0)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3454
#12 0x0000555557201184 in Js::InterpreterStackFrame::InterpreterHelper (function=0x7ffff272c2a0, args=..., 
    returnAddress=0x7ffff0700fa2, addressOfReturnAddress=0x7fffffffb988, isAsmJs=false)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:2054
#13 0x00005555571ff224 in Js::InterpreterStackFrame::InterpreterThunk (layout=0x7fffffffb9a0)
    at /home/gustavo/repos/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:1789
#14 0x00007ffff0700fa2 in ?? ()
```

This issue was found using QuickFuzz.

Regards,
Gustavo.

**Comment by jianchun** [comment]
Thanks for reporting this bug. The next line does IsCallable check and handling thus this has no release build impact:

```
RecyclableObject * constructor = RecyclableObject::FromVar(args[0]);
if (!JavascriptConversion::IsCallable(constructor) || args.Info.Count < 2)
{
    return JavascriptBoolean::ToVar(FALSE, scriptContext);
}
```
