### ISSUE TITLE
can chakracore.dll run on linux with dotnet core 2.0 ?

### ISSUE THREAD

**Issue by youngerier** [Microsoft/ChakraCore#4309]
code can be run with windows . but if I publish to linux 
use 
```
dotnet publish -r ubuntu.16.04-x64  .\IdentityClinet.csproj
```
it will be error bellow 
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'ChakraCore.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at ChakraHost.Hosting.Native.JsCreateRuntime(JavaScriptRuntimeAttributes attributes, JavaScriptThreadServiceCallback threadService, JavaScriptRuntime& runtime)
   at ChakraCore.Chakra.Run() in /root/ziggle/cpppp/ChakraCore/Chakra.cs:line 20
   at IdentityClinet.Program.Main(String[] args) in /root/ziggle/cpppp/ConsoleApp3/Program.cs:line 14
```

this is  the .csproj file
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RuntimeIdentifiers>win10-x64;ubuntu.16.04-x64</RuntimeIdentifiers>
        <TargetFramework>netcoreapp2.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="IdentityModel" Version="2.16.0" />
        <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\ChakraCore\ChakraCore.csproj" />
    </ItemGroup>
</Project>
```

**Comment by obastemur** [comment]
- You need to compile OR download ChakraCore for Ubuntu -> https://github.com/Microsoft/ChakraCore/wiki/Building-ChakraCore
- Use as is just another C/C++ library -> https://github.com/dotnet/core/issues/756

If you can succeed, please contribute a sample project to https://github.com/Microsoft/Chakra-Samples/tree/master/ChakraCore%20Samples

**Comment by digitalinfinity** [comment]
Hi @youngerier I believe @obastemur has answered your question- if you have follow ups, feel free to open new issues or hop on to our [gitter channel](https://gitter.im/Microsoft/ChakraCore).
