### ISSUE TITLE
ChakraCore crashes with assertion failure in UnicodeText.ICU.cpp

### ISSUE THREAD

**Issue by leeswimming** [Microsoft/ChakraCore#4526]
Debug build of ChakraCore received SIGILL with an ASSERTION FAILURE.

```
"friedrichstra\xDFe 14".toUpperCase(0xa >>> 0.0, "Sticky = true, RegExp.match() result");
```
$ ./ch 99-ef6afe1a505bf421c1e66223554e9ac60503ea96-1586.js 
ASSERTION 18040: (/data/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp, line 401) error == ApiError::NoError
 Failure: (error == ApiError::NoError)
Illegal instruction (core dumped)

$ file ch
ch: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32

OS: Ubuntu 16.04.3 LTS
Arch: x86_64

```
ASSERTION 18047: (/data/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp, line 401) error == ApiError::NoError
 Failure: (error == ApiError::NoError)

Thread 1 "ch" received signal SIGILL, Illegal instruction.
0x00007ffff610e51d in PlatformAgnostic::UnicodeText::ChangeStringCaseInPlace (
    caseFlags=PlatformAgnostic::UnicodeText::CaseFlagsUpper, stringToChange=0x7ffff7e35440 u"FRIEDRICHSTRASSE 1췍", 
    bufferLength=18) at /data/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp:401
401	            Assert(error == ApiError::NoError);
(gdb) bt
#0  0x00007ffff610e51d in PlatformAgnostic::UnicodeText::ChangeStringCaseInPlace (
    caseFlags=PlatformAgnostic::UnicodeText::CaseFlagsUpper, stringToChange=0x7ffff7e35440 u"FRIEDRICHSTRASSE 1췍", 
    bufferLength=18) at /data/ChakraCore/lib/Runtime/PlatformAgnostic/Platform/Linux/UnicodeText.ICU.cpp:401
#1  0x00007ffff5ef8335 in Js::JavascriptString::ToCaseCore (pThis=0x7ff7f0538c60, toCase=Js::JavascriptString::ToUpper)
    at /data/ChakraCore/lib/Runtime/Library/JavascriptString.cpp:2306
#2  0x00007ffff5ef9134 in Js::JavascriptString::EntryToUpperCase (function=0x7ff7f0424140, callInfo=...)
    at /data/ChakraCore/lib/Runtime/Library/JavascriptString.cpp:2235
#3  0x00007ffff5fb73ce in amd64_CallFunction () at /data/ChakraCore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#4  0x00007ffff5d1fed5 in Js::JavascriptFunction::CallFunction<true> (function=0x7ff7f0424140, 
    entryPoint=0x7ffff5ef8db0 <Js::JavascriptString::EntryToUpperCase(Js::RecyclableObject*, Js::CallInfo, ...)>, 
    args=..., useLargeArgCount=false) at /data/ChakraCore/lib/Runtime/Library/JavascriptFunction.cpp:1312
#5  0x00007ffff5b2f24e in Js::InterpreterStackFrame::OP_CallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffc110, playout=0x7ffff7e38320, function=0x7ff7f0424140, 
    flags=2, spreadIndices=0x0) at /data/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3918
#6  0x00007ffff5b2edfb in Js::InterpreterStackFrame::OP_ProfileCallCommon<Js::OpLayoutDynamicProfile<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > > (this=0x7fffffffc110, playout=0x7ffff7e38320, 
    function=0x7ff7f0424140, flags=0, profileId=0, inlineCacheIndex=0, spreadIndices=0x0)
    at /data/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3942
#7  0x00007ffff5b01d48 in Js::InterpreterStackFrame::OP_ProfiledCallIWithICIndex<Js::OpLayoutT_CallIWithICIndex<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > (this=0x7fffffffc110, playout=0x7ffff7e38320)
    at /data/ChakraCore/lib/Runtime/./Language/InterpreterStackFrame.h:503
#8  0x00007ffff59bc2e9 in Js::InterpreterStackFrame::ProcessProfiled (this=0x7fffffffc110)
    at /data/ChakraCore/lib/Runtime/Language/InterpreterHandler.inl:87
#9  0x00007ffff5950f5d in Js::InterpreterStackFrame::Process (this=0x7fffffffc110)
    at /data/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3415
#10 0x00007ffff5950186 in Js::InterpreterStackFrame::InterpreterHelper (function=0x7ff7f04c4240, args=..., 
    returnAddress=0x7ff7f0440fa2, addressOfReturnAddress=0x7fffffffc7b8, asmJsReturn=0x0)
    at /data/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:2002
#11 0x00007ffff594ee4b in Js::InterpreterStackFrame::InterpreterThunk (layout=0x7fffffffc7d0)
    at /data/ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:1733
#12 0x00007ff7f0440fa2 in ?? ()
#13 0x00007fffffffc7e0 in ?? ()
#14 0x00007ffff5fb73ce in amd64_CallFunction () at /data/ChakraCore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
Backtrace stopped: frame did not save the PC
```

**Comment by obastemur** [comment]
@leeswimming I assume you did build with default command line args?

**Comment by leeswimming** [comment]
```
./build.sh --debug
```
Yes. The command above is the one I used. Is that the reason of assertion failure?

**Comment by obastemur** [comment]
Yes/No. I asked because wanted to make sure that you weren’t using a custom ICU or no-icu.

**Comment by jackhorton** [comment]
Should be able to look at this next week, sorry for the delay!

**Comment by jackhorton** [comment]
This is because ChakraCore has historically assumed that converting strings to upper/lower case does not change the string length, due to the dependency on CharUpperBuff and CharLowerBuff on Windows. Fix should be inbound today or tomorrow.
