### ISSUE TITLE
Inconsistence when try to access an property inside the "with" scope

### ISSUE THREAD

**Issue by gfablima** [Microsoft/ChakraCore#5067]
Hi, 
there's an inconsistence when we try to access an property inside the "with" scope.

OS: Ubuntu 16.04 x64
Chakra: 1.10.0.0-beta

Step to reproduce:
```
var o = { f: "foo" };
with (o) {
  var desc = Object.getOwnPropertyDescriptor(this, "f");
  function f() {
    return "bar";
  }
  if (!(desc.value === undefined)) {
    throw new Error('expected: undefined, got: ' + desc.value);
  }
}
```
Actual results:
Error: expected: undefined, got: function f() {
  return "bar";
}

Expected results:
Pass without failures

V8 and Spidermonkey pass as expected, but Chakra and JavascriptCore returns the function f() inside "with" scope.

**Comment by fatcerberus** [comment]
Isn't this the expected behavior?  `function f()` gets hoisted and since it's in global scope it's assigned to the global object to be picked up by `getOwnPropertyDescriptor`.  V8 and SpiderMonkey's behavior seems stranger to me.

**Comment by fatcerberus** [comment]
With that said, your repro crashes outright in Node.js v10:
```
D:\temp>node f.js
D:\temp\f.js:7
  if (!(desc.value === undefined)) {
             ^

TypeError: Cannot read property 'value' of undefined
    at Object.<anonymous> (D:\temp\f.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
```

**Comment by dilijev** [comment]
Confirmed behavior difference.

```
## Source
var o = { f: "foo" };
with (o) {
  var desc = Object.getOwnPropertyDescriptor(this, "f");
  function f() {
    return "bar";
  }
  if (!(desc.value === undefined)) {
    print('expected: undefined, got: ' + desc.value);
  }
}
print('done')


#### jsvu-d8, jsvu-sm
done

#### jsvu-ch, jsvu-jsc
expected: undefined, got: function f() {
    return "bar";
  }
done
```

**Comment by pleath** [comment]
Chakra's is the behavior I would expect in sloppy mode. A binding for f is added to the global object.

**Comment by dilijev** [comment]
Maybe @bterlson can weigh in on spec?

**Comment by pleath** [comment]
Last I looked, V8 had left some aspects of block-scoped functions unimplemented due to compat concerns, though that may no longer be true.

**Comment by MikeHolman** [comment]
We should figure out whether this is really a bug or not. (And if it isn't a bug in our engine we should open bugs on FF/Chrome).

**Comment by curtisman** [comment]
@zenparsing can you confirm that Chakra's behavior matches the spec?

**Comment by zenparsing** [comment]
Annex B is tricky.

I think there is a spec violation in Chakra related to block scoped functions in sloppy mode (and unrelated to `with`):

For the following test case:

```js
function getF() { return f; }
{
  if (getF() === f) {
    throw new Error('Global var set before evaluating function declaration');
  }
  function f() { return "bar"; }
}
```

I see:

```
#### ch
Error: Global var set before evaluating function declaration

#### sm


#### v8


#### jsc
Error: Global var set before evaluating function declaration
```

According to [B3.3.2](https://tc39.github.io/ecma262/#sec-web-compat-globaldeclarationinstantiation), the global "var" binding should be initialized to `undefined`, and only set to the block-level value of `f` when the function declaration is evaluated.

**Comment by fatcerberus** [comment]
Kind of interesting that JSC produces the exact same error message as us.

**Comment by dilijev** [comment]
@fatcerberus the error is coming from the test case :P

**Comment by curtisman** [comment]
@zenparsing True enough. We should have a separate issue tracking that if there isn't one already.
But if this case inside the "with" is to spec, then we will close this particular issue.

**Comment by fatcerberus** [comment]
If the case @zenparsing describes is indeed a spec violation then the original case in this issue is too, since the `getOwnPropertyDescriptor` call comes before the function declaration and should therefore return a descriptor with `value: undefined`.

**Comment by zenparsing** [comment]
@curtisman I've created a new issue at #5340 to capture the function-in-block case.

@fatcerberus I think if we fix #5340 this one will be fixed as well.

**Comment by igor-simoes** [comment]
cinfuzz
