### ISSUE TITLE
ASSERTION 24541: (scopeSlotCount != 0) failed in Js::InterpreterStackFrame::NewScopeSlots

### ISSUE THREAD

**Issue by renatahodovan** [Microsoft/ChakraCore#5997]
###### ChakraCore version:

```
Checked revision: 39f9727ef
Build command: ./build.sh --debug
```

###### OS:

```
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```js
(function() {
    (function outer() {
        function $() {
            var $ = outer
        }
        with ($) { outer() }
    })()
})()
```

###### Backtrace:

```text
ASSERTION 24541: (ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp, line 7473) scopeSlotCount != 0
 Failure: (scopeSlotCount != 0)

Thread 1 "ch" received signal SIGILL, Illegal instruction.
0x0000555557a834ab in Js::InterpreterStackFrame::NewScopeSlots (this=0x7ffffffee360)
    at ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:7473
7473            Assert(scopeSlotCount != 0);
(gdb) bt
#0  0x0000555557a834ab in Js::InterpreterStackFrame::NewScopeSlots (this=0x7ffffffee360)
    at ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:7473
#1  0x0000555557a82b81 in Js::InterpreterStackFrame::InitializeClosures (this=0x7ffffffee360)
    at ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:1498
#2  0x0000555557bba374 in Js::InterpreterStackFrame::ProcessProfiled (this=0x7ffffffee360)
    at ChakraCore/lib/Runtime/Language/InterpreterLoop.inl:169
#3  0x0000555557a89bf0 in Js::InterpreterStackFrame::Process (this=0x7ffffffee360)
    at ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:3357
#4  0x0000555557a86e43 in Js::InterpreterStackFrame::InterpreterHelper (function=0x7ffff1f46780, args=..., 
    returnAddress=0x7ffff1d60f92, addressOfReturnAddress=0x7ffffffeed38, asmJsReturn=0x0)
    at ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:2051
#5  0x0000555557a84c23 in Js::InterpreterStackFrame::InterpreterThunk (layout=0x7ffffffeed50)
    at ChakraCore/lib/Runtime/Language/InterpreterStackFrame.cpp:1763
#6  0x00007ffff1d60f92 in ?? ()
#7  0x00007ffffffeed70 in ?? ()
#8  0x0000555558ded02e in amd64_CallFunction ()
    at ChakraCore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
Backtrace stopped: frame did not save the PC
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by renatahodovan** [comment]
It seems that the test case causes trouble (a fatal exception) in release build, too:

```text
Thread 4 "ch" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ff7f23b4700 (LWP 12541)]
0x00007ffff3de96e1 in ReportFatalException () from ChakraCore/out/Release/libChakraCore.so
(gdb) bt
#0  0x00007ffff3de96e1 in ReportFatalException () from ChakraCore/out/Release/libChakraCore.so
#1  0x00007ffff3de98c9 in Js::Throw::FatalInternalError(int) () from ChakraCore/out/Release/libChakraCore.so
#2  0x00007ffff3ce8884 in IRBuilder::DoClosureRegCheck(unsigned int) () from ChakraCore/out/Release/libChakraCore.so
#3  0x00007ffff3cd9404 in IRBuilder::Build() () from ChakraCore/out/Release/libChakraCore.so
#4  0x00007ffff3c7f497 in Func::TryCodegen() () from ChakraCore/out/Release/libChakraCore.so
#5  0x00007ffff3c7f253 in Func::Codegen(Memory::JitArenaAllocator*, JITTimeWorkItem*, ThreadContextInfo*, ScriptContextInfo*, JITOutputIDL*, Js::EntryPointInfo*, FunctionJITRuntimeInfo const*, JITTimePolymorphicInlineCacheInfo*, void*, Js::ScriptContextProfiler*, bool) () from ChakraCore/out/Release/libChakraCore.so
#6  0x00007ffff3daee64 in NativeCodeGenerator::CodeGen(Memory::PageAllocatorBase<Memory::VirtualAllocWrapper, Memory::SegmentBase<Memory::VirtualAllocWrapper>, Memory::PageSegmentBase<Memory::VirtualAllocWrapper> >*, CodeGenWorkItemIDL*, JITOutputIDL&, bool, Js::EntryPointInfo*) () from ChakraCore/out/Release/libChakraCore.so
#7  0x00007ffff3daf0fe in NativeCodeGenerator::CodeGen(Memory::PageAllocatorBase<Memory::VirtualAllocWrapper, Memory::SegmentBase<Memory::VirtualAllocWrapper>, Memory::PageSegmentBase<Memory::VirtualAllocWrapper> >*, CodeGenWorkItem*, bool) () from ChakraCore/out/Release/libChakraCore.so
#8  0x00007ffff3daf943 in NativeCodeGenerator::Process(JsUtil::Job*, JsUtil::ParallelThreadData*) () from ChakraCore/out/Release/libChakraCore.so
#9  0x00007ffff3ddcfae in JsUtil::BackgroundJobProcessor::Process(JsUtil::Job*, JsUtil::ParallelThreadData*) () from ChakraCore/out/Release/libChakraCore.so
#10 0x00007ffff3ddd0c5 in JsUtil::BackgroundJobProcessor::Run(JsUtil::ParallelThreadData*) () from ChakraCore/out/Release/libChakraCore.so
#11 0x00007ffff3ddc007 in JsUtil::BackgroundJobProcessor::StaticThreadProc(void*) () from ChakraCore/out/Release/libChakraCore.so
#12 0x00007ffff3bcf7a0 in CorUnix::CPalThread::ThreadEntry(void*) () from ChakraCore/out/Release/libChakraCore.so
#13 0x00007ffff73656db in start_thread (arg=0x7ff7f23b4700) at pthread_create.c:463
#14 0x00007ffff654b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
