### ISSUE TITLE
ASSERTION (instrPrev->IsBranchInstr() && instrPrev->AsBranchInstr()->IsConditional() && (!instrPrev->AsBranchInstr()->GetTarget()->isOpHelper || instrPrev->AsBranchInstr()->GetTarget()->m_noHelperAssert)) failed in DbCheckPostLower::Check

### ISSUE THREAD

**Issue by renatahodovan** [microsoft/ChakraCore#6006]
###### ChakraCore version:

```
Checked revision: 39f9727ef
Build command: ./build.sh --debug
```

###### OS:

```
Linux-4.15.0-43-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```js
function write() { 
    var y = function() {};   
    Object.prototype["qfxhma"] = function(){ throw $ };
    function shapeyConstructor($) {
        qfxhma();
        Object($, ({$: (function() {})}))
    }
    for (var $ in []) {
        try {   
            shapeyConstructor()
        }    catch ( $ ) { }
    }
    qfxhma = y;
}

for (var $;;) {
    write()
}
```

###### Backtrace:

```text
ASSERTION 22494: (ChakraCore/lib/Backend/DbCheckPostLower.cpp, line 130) (instrPrev->IsBranchInstr() && instrPrev->AsBranchInstr()->IsConditional() && (!instrPrev->AsBranchInstr()->GetTarget()->isOpHelper || instrPrev->AsBranchInstr()->GetTarget()->m_noHelperAssert))
 Failure: ((instrPrev->IsBranchInstr() && instrPrev->AsBranchInstr()->IsConditional() && (!instrPrev->AsBranchInstr()->GetTarget()->isOpHelper || instrPrev->AsBranchInstr()->GetTarget()->m_noHelperAssert)))

Thread 3 "ch" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ff7ebfff700 (LWP 22687)]
0x000055555a9cdaa7 in DbCheckPostLower::Check (this=0x7ff7ebffb0a0) at ChakraCore/lib/Backend/DbCheckPostLower.cpp:129
129                         Assert((instrPrev->IsBranchInstr() && instrPrev->AsBranchInstr()->IsConditional()
(gdb) bt
#0  0x000055555a9cdaa7 in DbCheckPostLower::Check (this=0x7ff7ebffb0a0) at ChakraCore/lib/Backend/DbCheckPostLower.cpp:129
#1  0x000055555a232287 in Func::EndPhase (this=0x7ff7ebffcbe0, tag=Js::Phase::RegAllocPhase, dump=true) at ChakraCore/lib/Backend/Func.cpp:1357
#2  0x000055555999536c in AutoCodeGenPhase::~AutoCodeGenPhase (this=0x7ff7ebffbd50) at ChakraCore/lib/Backend/Func.h:1127
#3  0x000055555a228b24 in Func::TryCodegen (this=0x7ff7ebffcbe0) at ChakraCore/lib/Backend/Func.cpp:495
#4  0x000055555a226ca0 in Func::Codegen (alloc=0x7ff7ebffd4a0, workItem=0x7ff7f04a1030, threadContextInfo=0x623000000198, scriptContextInfo=0x622000000158, outputData=0x7ff7ebffdad0, epInfo=
    0x7ffff1dac240, runtimeInfo=0x0, polymorphicInlineCacheInfo=0x7ffff1d1be20, codeGenAllocators=0x61a0000006d8, codeGenProfiler=0x0, isBackgroundJIT=true)
    at ChakraCore/lib/Backend/Func.cpp:323
#5  0x0000555559c07f42 in NativeCodeGenerator::CodeGen (this=0x613000000958, pageAllocator=0x615000001ef8, workItemData=0x6120000006c0, jitWriteData=..., foreground=false, epInfo=0x7ffff1dac240)
    at ChakraCore/lib/Backend/NativeCodeGenerator.cpp:894
#6  0x0000555559c0c3a6 in NativeCodeGenerator::CodeGen (this=0x613000000958, pageAllocator=0x615000001ef8, workItem=0x612000000698, foreground=false)
    at ChakraCore/lib/Backend/NativeCodeGenerator.cpp:1011
#7  0x0000555559c138b8 in NativeCodeGenerator::Process (this=0x613000000958, job=0x6120000006a0, threadData=0x615000001ed8) at ChakraCore/lib/Backend/NativeCodeGenerator.cpp:1907
#8  0x0000555559d66a1c in JsUtil::BackgroundJobProcessor::Process (this=0x612000000098, job=0x6120000006a0, threadData=0x615000001ed8) at ChakraCore/lib/Common/Common/Jobs.cpp:1037
#9  0x0000555559d67a1a in JsUtil::BackgroundJobProcessor::Run (this=0x612000000098, threadData=0x615000001ed8) at ChakraCore/lib/Common/Common/Jobs.cpp:1135
#10 0x0000555559d5e466 in JsUtil::BackgroundJobProcessor::StaticThreadProc (lpParam=0x615000001ed8) at ChakraCore/lib/Common/Common/Jobs.cpp:1319
#11 0x00005555565f12b2 in CorUnix::CPalThread::ThreadEntry (pvParam=0x61c000001080) at ChakraCore/pal/src/thread/pal_thread.cpp:1605
#12 0x00005555563ffb1f in __asan::AsanThread::ThreadStart(unsigned long, __sanitizer::atomic_uintptr_t*) ()
#13 0x00007ffff73656db in start_thread (arg=0x7ff7ebfff700) at pthread_create.c:463
#14 0x00007ffff66cc88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

**Comment by MikeHolman** [comment]
No repro on latest master
