### ISSUE TITLE
Fail to throw TypeError in Promise.race

### ISSUE THREAD

**Issue by sunlili** [microsoft/ChakraCore#6367]
The bug can reproduce in ch version 1.11.15.0.
Running following code:
```
var obj = new Object();
Promise.race(obj);
```

According to ECMA manual, since `obj` is not iterable object, a  TypeError should be thrown. However, ch output nothing.

ISec Lab
2019.12.25

**Comment by fatcerberus** [comment]
Specifically, it should result in a *rejected promise*, rejected with the aforementioned TypeError.

```
Welcome to Node.js v13.6.0.
Type ".help" for more information.
> Promise.race(new Object())
Promise {
  <rejected> TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
      at Function.race (<anonymous>)
      at repl:1:9
      at Script.runInThisContext (vm.js:120:20)
      at REPLServer.defaultEval (repl.js:427:29)
      at bound (domain.js:429:14)
      at REPLServer.runBound [as eval] (domain.js:442:12)
      at REPLServer.onLine (repl.js:754:10)
      at REPLServer.emit (events.js:333:22)
      at REPLServer.EventEmitter.emit (domain.js:485:12)
      at REPLServer.Interface._onLine (readline.js:323:10)
}
> (node:12088) UnhandledPromiseRejectionWarning: TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.race (<anonymous>)
    at repl:1:9
    at Script.runInThisContext (vm.js:120:20)
    at REPLServer.defaultEval (repl.js:427:29)
    at bound (domain.js:429:14)
    at REPLServer.runBound [as eval] (domain.js:442:12)
    at REPLServer.onLine (repl.js:754:10)
    at REPLServer.emit (events.js:333:22)
    at REPLServer.EventEmitter.emit (domain.js:485:12)
    at REPLServer.Interface._onLine (readline.js:323:10)
(node:12088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by fatcerberus** [comment]
Assuming that the Node.js behavior above is correct, then CC also exhibits the correct behavior, though the error message itself could use some work 😛 

```
Promise.race(new Object());
```

```
uncaught JavaScript exception

TypeError: Function expected
   at Module code (src/main.js:17:1)
```

The reason you see no error by default is because ch ignores the unhandled promise rejection.

**Comment by rhuanjl** [comment]
If you run ch with the flag -TrackRejectedPromises  you should get the output you’re expecting.

**Comment by rhuanjl** [comment]
This isn't actually a bug, the correct error is provided as a promise rejection.
